#Theme

enable_ligatures yes

cursor_shape beam
cursor_blink_interval 0.6

shell_integration enabled

#Opacity
window_padding_width 10
background_opacity 0.7

#Font
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 14

line_height 1
letter_spacing 0.4

# Open new window
map ctrl+shift+enter new_window

# New tab
map ctrl+t new_tab

# Close tab
map ctrl+shift+q close_tab

# Switch tabs
map ctrl+right next_tab
map ctrl+left previous_tab

# Copy / paste
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
include 1984-Dark.conf
# END_KITTY_THEME
