#!/usr/bin/env bash

set -euo pipefail

DIR="$HOME/Pictures/Screenshots"

mkdir -p "$DIR"

FILE="$DIR/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png"

GEOMETRY="$(slurp)" || exit 0

grim -g "$GEOMETRY" "$FILE"

wl-copy <"$FILE"

swappy -f "$FILE"
