[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = ICTDDpcLrHMKSwjaDubQsaBt/KpN/5wUv6ZceCwGqEo=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# JP-FREE#13
PublicKey = mJ0V3c17L3UEJJ7BSf9iAdCNJLWT1/5I/bPycxITSi0=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 212.102.51.247:51820