[Interface]
# Bouncing = 3
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = iBUwWogfJpC4A3RT6Rv2/wNAi7lswvGb2wGecAioHGk=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# JP-FREE#14
PublicKey = fdtybgb+Y6FAiUR1/AlJ6vNm4D5MkHLJrvvNwdnNPn8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 138.199.21.198:51820