[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = WMxSsCtpMj7zpSioXyKo28VvBmkg2sGbeKwPF0MnnU8=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# JP-FREE#15
PublicKey = rnrZQSK5IeTCzh60Ghv/TEaUIbD7IprzdoCJjE5E9Sc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 37.19.205.202:51820