[Interface]
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = WOBL9T6jjANOE1lmwT9bHGQ5XCLj5hZv7l14tqS6pWw=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# JP-FREE#31
PublicKey = A51GuD3kVrG+bw0ZYnmFvCpRDI6VktCHGRCTfLVf1jw=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.88.103.33:51820

PersistentKeepalive = 25