[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = 4NiURgXFipaPbsr/tdGaK1suZA6Soa2cR8C76AII9W4=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# JP-FREE#33
PublicKey = qhEO97nKps2D1JsZjw3AiSuVJVbrBROV3Gpvong0hgI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.88.103.161:51820