[Interface]
# Bouncing = 3
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = 6Csfwthd8WHPJlFNWvNTuMyOw5Z2zyuxpMK7m0tqaVs=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# NL-FREE#33
PublicKey = 5+Pfgs2q2WVR1/E+wtAtHmts+wVaJCPcqXLEmO/tDD8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 185.177.124.206:51820