[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = YMhBeaWEb90m7//sYXMCiX3COzIJ6LAQJPmKXcHPZlk=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#12
PublicKey = 1Fe25chEMe3i5ODyDeHhC94UY63O4vAyMw1KDgxcAk8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.40.62.26:51820