[Interface]
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = GNw24sc4KuQbp8C/DfzcViLYWYuDyyzoYZlTkkh4BW0=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#13
PublicKey = emXbYiKqKRiZ2Q8uZCBley49t1FwwF88DfJX27A/WCU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.40.62.31:51820