[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 4HLfiui1oaV2sNLMRp7OqzA42n9XEYzF6HF7Pc0rK1o=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#22
PublicKey = rnNqkTj0nfpgF0G06QU8IIzU5fCvtXVQBmTvJ1hlgCo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.40.62.36:51820