[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = cC0KjnU8h4bgaBZ52x7M+N9CsbegvWxRN0I3Pe/cmGI=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#36
PublicKey = +tBxOtFy6U050wKXUHW16Ya8gzRVoAGdSZGQ2PokrGA=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.22.84.149:51820

PersistentKeepalive = 25