[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = QAl9C7lRi4WLw08jFWbWxPdyV2lILV5DjISHHjm/T0k=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#85
PublicKey = gDmb0KtRVAd2UYnKs0UkXqS0tgcqk7UNw6yTb+loQ1c=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.40.51.230:51820