[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = sBzzrDRn36xLSHKGbCeaEViaDx66ORiV1bvPg2A1TkQ=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#86
PublicKey = oOweBQMuJhyG8mY9D/zoRmnxZ1V6HcyND5HGKbWyZDg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.34.251.134:51820