#Test
F12 show-text "INPUT.CONF LOADED" 3000

# Playback
SPACE cycle pause
s stop
n playlist-next
p playlist-prev
t show-text "${playback-time} / ${time-remaining}" 3000
f cycle fullscreen
ESC set fullscreen no

] add speed 0.1
+ add speed 0.1
[ add speed -0.1
- add speed -0.1
= set speed 1.0

e seek 10
q seek -10

# Seeking
Alt+LEFT seek -10
Alt+RIGHT seek 10

Ctrl+LEFT seek -60
Ctrl+RIGHT seek 60

Shift+LEFT seek -180
Shift+RIGHT seek 180

# Volume
m cycle mute
UP add volume 5
DOWN add volume -5
WHEEL_UP add volume 5
WHEEL_DOWN add volume -5

# Audio
a cycle audio
Ctrl+[ add audio-delay -0.1
Ctrl+] add audio-delay 0.1

# Video
z cycle-values video-zoom 0 0.5 1 1.5 2
c cycle-values video-aspect-override "-1" "16:9" "4:3" "21:9"
o cycle osd-level

# Subtitles
v cycle sub
g cycle sub-visibility
Ctrl+h add sub-delay 0.1
Ctrl+g add sub-delay -0.1

# Subtitle size
Ctrl+= add sub-scale 0.1
Ctrl+- add sub-scale -0.1

# Reset subtitle size
Ctrl+0 set sub-scale 1.0

# Advanced
d frame-step

# Information
Ctrl+i script-binding stats/display-stats-toggle

# Quit
Ctrl+q quit
