# =====================================================
# General
# =====================================================

general {
    lock_cmd = pidof hyprlock || ~/.config/niri/scripts/lock-screen
    after_sleep_cmd = niri msg action power-on-monitors
}

# =====================================================
# Lock Screen
# =====================================================

listener {
    timeout = 300
    on-timeout = pidof hyprlock || ~/.config/niri/scripts/lock-screen
}

# =====================================================
# Display Power Management
# =====================================================

listener {
    timeout = 600
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

# =====================================================
# Suspend
# =====================================================

listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
